pipeline {
    agent any

    environment {
        // Environment variables, if needed
        CALCULATOR_URL = 'localhost:5001'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Ensure gradlew is executable') {
            steps {
                sh 'chmod +x Chapter09/sample1/gradlew'
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    dir('Chapter09/sample1') {
                        sh './gradlew clean build --no-daemon'
                        sh './gradlew test jacocoTestReport --no-daemon'
                    }
                }
            }
        }

        stage('Code Coverage') {
            steps {
                script {
                    dir('Chapter09/sample1') {
                        sh './gradlew jacocoTestReport --no-daemon'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Specify the correct directory for the Dockerfile
                    dir('Chapter08/sample1') {
                        sh 'docker build -t localhost:5001/calculator:1.0 .'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh 'docker push localhost:5001/calculator:1.0'
                }
            }
        }

        stage('Test Docker Container') {
            steps {
                script {
                    sh '''
                        docker run -d --name calculator localhost:5001/calculator:1.0
                        sleep 5
                        curl -s localhost:5001:8080/div?a=6&b=2 | grep -q 3 && echo pass || echo fail
                        curl -s localhost:5001:8080/div?a=6&b=0 | grep -q error && echo pass || echo fail
                    '''
                }
            }
        }

        stage('Cleanup') {
            steps {
                script {
                    sh 'docker rm -f calculator || true'
                }
            }
        }

        stage('Post Actions') {
            steps {
                cleanWs()
                echo 'Pipeline finished successfully!'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace'
            cleanWs()
        }
    }
}

